# Generated by Django 3.0.8 on 2021-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.EmailField(default='', max_length=255)),
                ('mobile', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=255)),
                ('locate', models.BooleanField(default=False)),
                ('search_active', models.BooleanField(default=False)),
                ('law_school', models.CharField(blank=True, default='', max_length=255)),
                ('grad_year', models.IntegerField(default=0)),
                ('bar_admit_date', models.CharField(blank=True, default='', max_length=255)),
                ('undergrad_school', models.CharField(blank=True, default='', max_length=255)),
                ('undergrad_area', models.CharField(blank=True, default='', max_length=255)),
                ('undergrad_year', models.CharField(blank=True, default='', max_length=255)),
                ('bar_no', models.CharField(blank=True, default='', max_length=255)),
                ('admitted_practice', models.CharField(blank=True, default='', max_length=255)),
                ('practice_time', models.CharField(blank=True, default='', max_length=255)),
                ('longest_tenure', models.CharField(blank=True, default='', max_length=255)),
                ('average_tenure', models.CharField(blank=True, default='', max_length=255)),
                ('current_tenure', models.CharField(blank=True, default='', max_length=255)),
                ('past_bar_companies_no', models.CharField(blank=True, default='', max_length=255)),
                ('primary_area', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
