# Generated by Django 3.0.8 on 2021-12-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='billable',
            new_name='is_billable',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='private',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='matter',
            name='billing_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matter',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matter',
            name='open_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='last_action',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='matter',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='matter_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='next_action',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_nature',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='matter_id',
            field=models.IntegerField(default=0),
        ),
    ]
