# Generated by Django 3.0.8 on 2021-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211212_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='matter_id',
        ),
        migrations.AddField(
            model_name='matter',
            name='alerts',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='involved',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='jurisdiction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='narrative',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='opposing_counsel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='status_limitaion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='total_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='when',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='where',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='witnesses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='assign_by',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='assign_to',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='billing_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
