# Generated by Django 3.0.8 on 2021-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211214_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='when',
            field=models.DateTimeField(null=True),
        ),
    ]
