# Generated by Django 3.0.8 on 2021-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211214_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='billing_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='close_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='open_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='when',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
