# Generated by Django 3.0.8 on 2021-12-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211214_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matter',
            old_name='close_date',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='matter',
            old_name='open_date',
            new_name='open',
        ),
    ]
