# Generated by Django 3.0.8 on 2021-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211214_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='close',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='open',
        ),
        migrations.AddField(
            model_name='matter',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='open_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='billing_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='when',
            field=models.DateField(null=True),
        ),
    ]
