# Generated by Django 3.0.8 on 2021-12-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211214_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
