# Generated by Django 3.0.8 on 2021-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211214_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_billable',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='matter',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='matter_contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='matter_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
