# Generated by Django 3.0.8 on 2021-12-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211215_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
