# Generated by Django 3.0.8 on 2021-12-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211215_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(default=0, null=True)),
                ('matter_name', models.IntegerField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255, null=True)),
                ('hard', models.BooleanField(default=False, null=True)),
                ('soft', models.BooleanField(default=False, null=True)),
                ('unit', models.IntegerField(default=0, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('file', models.CharField(default='', max_length=500, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('detail', models.CharField(max_length=800, null=True)),
                ('bill_by', models.IntegerField(default=0, null=True)),
                ('billable', models.BooleanField(default=False, null=True)),
                ('note', models.CharField(max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
