# Generated by Django 3.0.8 on 2021-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ledgertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, default='', max_length=255)),
                ('m_name', models.CharField(blank=True, default='', max_length=255)),
                ('l_name', models.CharField(blank=True, default='', max_length=255)),
                ('c_email', models.EmailField(default='', max_length=255)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('time_zone', models.CharField(blank=True, default='', max_length=255)),
                ('group', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('bar_no', models.IntegerField(blank=True, default=0, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('suite', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zip', models.IntegerField(blank=True, default=0, null=True)),
                ('ext', models.IntegerField(blank=True, default=0, null=True)),
                ('mobile', models.IntegerField(blank=True, default=0, null=True)),
                ('home', models.IntegerField(blank=True, default=0, null=True)),
                ('work_no', models.IntegerField(blank=True, default=0, null=True)),
                ('p_email', models.EmailField(default='', max_length=255)),
                ('phone_ext', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
