# Generated by Django 3.0.8 on 2021-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_group_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('webiste', models.CharField(blank=True, default='', max_length=255)),
                ('ger_email', models.EmailField(blank=True, default='', max_length=255)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=255)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('suite', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zip', models.IntegerField(blank=True, default=0, null=True)),
                ('plus_4', models.IntegerField(blank=True, default=0, null=True)),
                ('client_no', models.IntegerField(blank=True, default=0, null=True)),
                ('f_name', models.CharField(blank=True, default='', max_length=255)),
                ('l_name', models.CharField(blank=True, default='', max_length=255)),
                ('dob', models.CharField(blank=True, default='', max_length=255)),
                ('ssn', models.IntegerField(blank=True, default=0, null=True)),
                ('mobile_no', models.IntegerField(blank=True, default=0, null=True)),
                ('home_no', models.IntegerField(blank=True, default=0, null=True)),
                ('office_no', models.IntegerField(blank=True, default=0, null=True)),
                ('fax_no', models.IntegerField(blank=True, default=0, null=True)),
                ('other_no', models.IntegerField(blank=True, default=0, null=True)),
                ('email_1', models.EmailField(blank=True, default='', max_length=255)),
                ('email_2', models.EmailField(blank=True, default='', max_length=255)),
                ('email_3', models.EmailField(blank=True, default='', max_length=255)),
                ('street2', models.CharField(blank=True, default='', max_length=255)),
                ('suite2', models.CharField(blank=True, default='', max_length=255)),
                ('city2', models.CharField(blank=True, default='', max_length=255)),
                ('state2', models.CharField(blank=True, default='', max_length=255)),
                ('zip2', models.IntegerField(blank=True, default=0, null=True)),
                ('plus_42', models.IntegerField(blank=True, default=0, null=True)),
                ('office', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.CharField(blank=True, default='', max_length=255)),
                ('memmber', models.CharField(blank=True, default='', max_length=255)),
                ('assign_to', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.CharField(blank=True, default='', max_length=255)),
                ('relation', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
